const { SlashCommandBuilder, PermissionFlagsBits } = require('discord.js');
const c=(name,desc,perm,execute)=>({data:new SlashCommandBuilder().setName(name).setDescription(desc).setDefaultMemberPermissions(perm),permission:perm,execute});
const target=s=>s.addUserOption(o=>o.setName('user').setDescription('Target user').setRequired(true));
const commands=[];
commands.push(c('kick','Kick a member',PermissionFlagsBits.KickMembers,async(i)=>{const u=i.options.getUser('user',true);const m=await i.guild.members.fetch(u.id);await m.kick('Moderation command');await i.reply(`👢 Kicked ${u.tag}`);}));
commands.push(c('ban','Ban a member',PermissionFlagsBits.BanMembers,async(i)=>{const u=i.options.getUser('user',true);const m=await i.guild.members.fetch(u.id);await m.ban({reason:'Moderation command'});await i.reply(`🔨 Banned ${u.tag}`);}));
commands.push(c('unban','Unban by user ID',PermissionFlagsBits.BanMembers,async(i)=>{const id=i.options.getString('id',true);await i.guild.members.unban(id,'Moderation command');await i.reply(`✅ Unbanned ${id}`);}));
commands.push(c('timeout','Timeout a member',PermissionFlagsBits.ModerateMembers,async(i)=>{const u=i.options.getUser('user',true);const m=await i.guild.members.fetch(u.id);const mins=i.options.getInteger('minutes',true);await m.timeout(mins*60000,'Moderation command');await i.reply(`⏳ Timed out ${u.tag} for ${mins}m`);}));
commands.push(c('untimeout','Remove timeout',PermissionFlagsBits.ModerateMembers,async(i)=>{const u=i.options.getUser('user',true);const m=await i.guild.members.fetch(u.id);await m.timeout(null,'Moderation command');await i.reply(`✅ Removed timeout from ${u.tag}`);}));
commands.push(c('purge','Delete recent messages',PermissionFlagsBits.ManageMessages,async(i)=>{const amount=i.options.getInteger('amount',true);const msgs=await i.channel.bulkDelete(amount,true);await i.reply({content:`🧹 Deleted ${msgs.size} messages`,ephemeral:true});}));
commands.push(c('slowmode','Set channel slowmode',PermissionFlagsBits.ManageChannels,async(i)=>{const seconds=i.options.getInteger('seconds',true);await i.channel.setRateLimitPerUser(seconds);await i.reply(`🐌 Slowmode set to ${seconds}s`);}));
commands.push(c('lock','Lock current channel',PermissionFlagsBits.ManageChannels,async(i)=>{await i.channel.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:false});await i.reply('🔒 Channel locked.');}));
commands.push(c('unlock','Unlock current channel',PermissionFlagsBits.ManageChannels,async(i)=>{await i.channel.permissionOverwrites.edit(i.guild.roles.everyone,{SendMessages:null});await i.reply('🔓 Channel unlocked.');}));
commands.push(c('warn','Warn a member',PermissionFlagsBits.ModerateMembers,async(i)=>{const u=i.options.getUser('user',true);const reason=i.options.getString('reason')||'No reason provided';const n=await i.client.db.increment(i.guildId,`warns:${u.id}`,1);await i.reply(`⚠️ Warned ${u.tag} (#${n}) • ${reason}`);}));
for(const x of commands){if(['kick','ban','unban','timeout','untimeout','warn'].includes(x.data.name)) target(x.data);if(x.data.name==='timeout')x.data.addIntegerOption(o=>o.setName('minutes').setDescription('Minutes').setMinValue(1).setMaxValue(40320).setRequired(true));if(x.data.name==='unban')x.data.addStringOption(o=>o.setName('id').setDescription('User ID').setRequired(true));if(x.data.name==='timeout'||x.data.name==='warn'){}if(x.data.name==='warn')x.data.addStringOption(o=>o.setName('reason').setDescription('Reason'));if(x.data.name==='purge')x.data.addIntegerOption(o=>o.setName('amount').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true));if(x.data.name==='slowmode')x.data.addIntegerOption(o=>o.setName('seconds').setDescription('0-21600').setMinValue(0).setMaxValue(21600).setRequired(true));}
module.exports={commands};
