const http=require('node:http');
const fs=require('node:fs');
const path=require('node:path');
const yaml=require('js-yaml');
let server=null;
function escape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function brand(client){const b=client.config.branding||{};return{server:b.serverName||'RealmsNetwork',bot:b.botName||'RealmsNetwork Bot',color:b.embedColor||'#8b5cf6',footer:b.footer||b.serverName||'RealmsNetwork'};}
function page(client,cfg){const b=brand(client),uptime=Math.floor((Date.now()-client.metrics.startedAt)/1000),rows=[['Environment',client.config.runtime?.environment||'production'],['Database',client.db?.type||'none'],['Remote DB',client.db?.isRemote?'yes':'no'],['Guilds',client.guilds.cache.size],['Modules',client.modules.size],['Commands',client.commands.size+client.contextMenus.size],['Commands used',client.metrics.commands],['Errors',client.metrics.errors],['Uptime',`${uptime}s`]];const controls=cfg.readOnly!==false?'<p>Read-only mode is enabled.</p>':`<section class="controls"><input id="token" type="password" placeholder="Admin token"><button onclick="reload()">Reload commands</button><h2>Modules</h2><div id="mods">${[...client.modules.keys()].map(name=>`<button onclick="toggle(${JSON.stringify(name)})">${escape(name)}</button>`).join(' ')||'No modules loaded.'}</div></section><script>const token=()=>document.getElementById('token').value;async function api(path,method='POST',body){const r=await fetch(path,{method,headers:{'content-type':'application/json','authorization':'Bearer '+token()},body:body?JSON.stringify(body):undefined});return r.json()}async function reload(){const r=await api('/api/reload');alert(r.message||r.error||'Done')}async function toggle(name){const enabled=confirm('Enable module '+name+'?\nCancel disables it.');const r=await api('/api/module','POST',{module:name,enabled});alert(r.message||r.error||'Saved');location.reload()}</script>`;return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escape(b.bot)}</title><style>body{margin:0;background:#09070d;color:#eee;font:15px system-ui;padding:32px}main{max-width:1000px;margin:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card{background:#0f0b14;border:1px solid #29202f;border-radius:14px;padding:18px}.label{opacity:.6;font-size:12px;text-transform:uppercase}.value{font-size:24px;margin-top:8px;color:${escape(b.color)}}h1{color:${escape(b.color)}}input,button{background:#0f0b14;color:#eee;border:1px solid #392a44;border-radius:8px;padding:10px;margin:4px}button{cursor:pointer}</style></head><body><main><h1>${escape(b.server)} • ${escape(b.bot)}</h1><p>Authenticated production administration dashboard</p><section class="grid">${rows.map(([k,v])=>`<div class="card"><div class="label">${escape(k)}</div><div class="value">${escape(v)}</div></div>`).join('')}</section>${controls}</main></body></html>`;}
function authorized(req,token){const header=req.headers.authorization?.replace(/^Bearer\s+/i,'');return Boolean(token&&header===token);}
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data));}
async function body(req){let raw='';for await(const chunk of req)raw+=chunk;if(raw.length>65536)throw new Error('Request too large');return raw?JSON.parse(raw):{};}
async function initialize(client,config,moduleConfig){const cfg=moduleConfig;if(cfg.enabled!==true)return;const tokenEnv=cfg.tokenEnv||'DASHBOARD_TOKEN';if(!process.env[tokenEnv]){console.warn(`[Dashboard] ${tokenEnv} is not set; dashboard will not start.`);return;}const host=cfg.host||'127.0.0.1',port=Number(cfg.port||8787),modulesRoot=path.join(__dirname,'..');server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`http://${req.headers.host||host}`);if(url.pathname==='/health')return json(res,200,{ok:true,uptime:Math.floor((Date.now()-client.metrics.startedAt)/1000),database:client.db?.type||'none'});if(!authorized(req,process.env[tokenEnv]))return json(res,401,{error:'Unauthorized'});if(url.pathname==='/api/status')return json(res,200,{ok:true,metrics:client.metrics,guilds:client.guilds.cache.size,modules:[...client.modules.keys()],commands:client.commands.size+client.contextMenus.size,database:client.db?.type||'none'});if(url.pathname==='/api/reload'&&req.method==='POST'){if(cfg.readOnly!==false||cfg.allowReload===false)return json(res,403,{error:'Reload controls are disabled'});await require('../../lib/module-loader').refreshCommands(client,client.config);return json(res,200,{ok:true,message:'Command registry reloaded'});}if(url.pathname==='/api/module'&&req.method==='POST'){if(cfg.readOnly!==false||cfg.allowModuleToggle===false)return json(res,403,{error:'Module controls are disabled'});const data=await body(req),name=String(data.module||'');if(!/^[a-zA-Z0-9_-]+$/.test(name))return json(res,400,{error:'Invalid module name'});const dir=path.join(modulesRoot,name),file=path.join(dir,'config.yml');if(!fs.existsSync(file))return json(res,404,{error:'Module not found'});const current=yaml.load(fs.readFileSync(file,'utf8'))||{};current.enabled=data.enabled===true;fs.writeFileSync(file,yaml.dump(current,{noRefs:true,lineWidth:-1}),'utf8');await require('../../lib/module-loader').refreshCommands(client,client.config);return json(res,200,{ok:true,message:`${name} is now ${current.enabled?'enabled':'disabled'}`});}if(url.pathname!=='/')return json(res,404,{error:'Not found'});res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(page(client,cfg));}catch(e){console.error('[Dashboard]',e);json(res,500,{error:e.message});}});server.listen(port,host,()=>console.log(`[Dashboard] Listening on http://${host}:${port}`));}
async function destroy(){await new Promise(resolve=>server?server.close(resolve):resolve());server=null;}
module.exports={initialize,destroy};
