require('dotenv').config({ quiet: true });
const fs=require('node:fs');const path=require('node:path');const yaml=require('js-yaml');
const {Client,Collection,Events,GatewayIntentBits,Partials,REST,Routes}=require('discord.js');
const {loadConfig}=require('./lib/config');const {createDatabase}=require('./lib/database');const {loadModules,refreshCommands}=require('./lib/module-loader');const {authorize}=require('./lib/permissions');
const config=loadConfig();const moduleConfigPath=name=>path.join(__dirname,'modules',name,'config.yml');const enabled=name=>{try{const file=moduleConfigPath(name);if(fs.existsSync(file))return yaml.load(fs.readFileSync(file,'utf8'))?.enabled===true;}catch{}return config[name]?.enabled===true;};
const intents=[GatewayIntentBits.Guilds];if(['ai','automod','logging','leveling','automation','engagement','autoresponder','messageEmbedder','highlights','feeds','forms','tags'].some(enabled)||config.customModules?.enabled||config.prefix?.enabled)intents.push(GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent);if(['welcome','logging','autorole','countryballs'].some(enabled))intents.push(GatewayIntentBits.GuildMembers);if(['logging','security'].some(enabled))intents.push(GatewayIntentBits.GuildModeration);if(['tickets','community','roles','countryballs','starboard'].some(enabled))intents.push(GatewayIntentBits.GuildMessageReactions);
const client=new Client({intents:[...new Set(intents)],partials:[Partials.Channel,Partials.Message,Partials.GuildMember,Partials.User,Partials.Reaction]});client.config=config;client.commands=new Collection();client.contextMenus=new Collection();client.prefixCommands=new Map();client.modules=new Collection();client.cooldowns=new Map();client.metrics={commands:0,prefixCommands:0,errors:0,startedAt:Date.now(),events:0};client.framework=Object.freeze({version:4,name:'RealmsNetwork Bot Framework',reloadCommands:()=>refreshCommands(client,config),registerPrefixCommand:(name,handler)=>client.prefixCommands.set(String(name).toLowerCase(),handler)});
async function deployCommands(){const c=config.commands||{};if(c.autoDeploy!==true||!process.env.DISCORD_TOKEN||!process.env.DISCORD_CLIENT_ID)return;const body=[...client.commands.values()].map(x=>x.data.toJSON()).concat([...client.contextMenus.values()].map(x=>x.data.toJSON()));const rest=new REST({version:'10'}).setToken(process.env.DISCORD_TOKEN);const route=c.guildOnly!==false&&config.guildId&&config.guildId!=='YOUR_GUILD_ID_HERE'?Routes.applicationGuildCommands(process.env.DISCORD_CLIENT_ID,config.guildId):Routes.applicationCommands(process.env.DISCORD_CLIENT_ID);await rest.put(route,{body});console.log(`[Commands] Synced ${body.length} application commands`);}
function commandSignature(){return JSON.stringify({slash:[...client.commands.values()].map(x=>x.data.toJSON()).sort((a,b)=>a.name.localeCompare(b.name)),context:[...client.contextMenus.values()].map(x=>x.data.toJSON()).sort((a,b)=>String(a.name).localeCompare(String(b.name))) });}
function cooldownSeconds(command){return Math.max(0,Number(command.cooldown??config.commands?.defaultCooldownSeconds??0));}function checkCooldown(command,userId){const seconds=cooldownSeconds(command);if(!seconds)return 0;const key=`${userId}:${command.data.name}`,now=Date.now(),previous=client.cooldowns.get(key)||0,remaining=seconds*1000-(now-previous);if(remaining>0)return Math.ceil(remaining/1000);client.cooldowns.set(key,now);if(client.cooldowns.size>Number(config.runtime?.cacheSize||1000)*2)for(const[k,ts]of client.cooldowns)if(now-ts>seconds*1000)client.cooldowns.delete(k);return 0;}
function getCommand(interaction){if(interaction.isChatInputCommand())return client.commands.get(interaction.commandName);if(interaction.isUserContextMenuCommand()||interaction.isMessageContextMenuCommand())return client.contextMenus.get(interaction.commandName);return null;}
async function executeInteraction(interaction){const command=getCommand(interaction);if(!command)return;try{if(!authorize(interaction,command,client.config))return interaction.reply({content:client.config.branding?.permissionDenied||'You do not have permission to use this command.',ephemeral:true});const left=checkCooldown(command,interaction.user.id);if(left)return interaction.reply({content:`Please wait **${left}s** before using this again.`,ephemeral:true});client.metrics.commands++;await command.execute(interaction,client);}catch(e){client.metrics.errors++;console.error(`[Command] ${interaction.commandName}:`,e);const payload={content:client.config.branding?.errorMessage||'Something went wrong while running that command.',ephemeral:true};if(interaction.replied||interaction.deferred)await interaction.followUp(payload).catch(()=>{});else await interaction.reply(payload).catch(()=>{});}}
async function executePrefix(message){const p=config.prefix||{};if(p.enabled!==true||!message.guild||message.author.bot)return;const prefixes=Array.isArray(p.prefixes)&&p.prefixes.length?p.prefixes:['!'];const prefix=prefixes.find(x=>message.content.startsWith(x))||(p.mentionPrefix&&client.user&&message.content.startsWith(`<@${client.user.id}>`)?`<@${client.user.id}>`:null);if(!prefix)return;const body=message.content.slice(prefix.length).trim();if(!body)return;const parts=body.split(/\s+/),name=parts.shift().toLowerCase(),handler=client.prefixCommands.get(name);if(!handler)return;try{if(handler.cooldown&&checkCooldown({data:{name},cooldown:handler.cooldown},message.author.id))return;client.metrics.prefixCommands++;await handler(message,{args:parts,prefix,name,client,config});}catch(e){client.metrics.errors++;console.error(`[Prefix] ${name}:`,e);if(config.prefix.errorMessage)await message.reply(config.prefix.errorMessage).catch(()=>{});}}
function startAutoRefresh(){const c=config.commands||{};if(c.autoRefresh!==true)return;let signature=commandSignature();const timer=setInterval(async()=>{try{await refreshCommands(client,config,true);const next=commandSignature();if(next!==signature){signature=next;await deployCommands();}}catch(e){console.error('[Commands] Auto-refresh failed:',e.message);}},Math.max(1000,Number(c.refreshIntervalMs||5000)));timer.unref?.();}
async function start(){if(!process.env.DISCORD_TOKEN||process.env.DISCORD_TOKEN==='YOUR_BOT_TOKEN_HERE')throw new Error('DISCORD_TOKEN is missing');client.db=await createDatabase(config);await loadModules(client,config);client.on(Events.InteractionCreate,executeInteraction);if(config.prefix?.enabled===true)client.on(Events.MessageCreate,message=>{client.metrics.events++;return executePrefix(message);});client.once(Events.ClientReady,async c=>{client.metrics.readyAt=Date.now();console.log(`[Bot] Online as ${c.user.tag} | ${c.guilds.cache.size} guilds | ${client.commands.size+client.contextMenus.size} commands | ${client.modules.size} modules | db=${client.db.type}`);await deployCommands().catch(e=>console.error('[Commands] Deploy failed:',e.message));startAutoRefresh();});process.once('SIGINT',shutdown);process.once('SIGTERM',shutdown);process.on('uncaughtException',e=>{client.metrics.errors++;console.error('[Runtime] Uncaught exception:',e);if(config.runtime?.crashProtection===false)process.exit(1);});process.on('unhandledRejection',e=>{client.metrics.errors++;console.error('[Runtime] Unhandled rejection:',e);});await client.login(process.env.DISCORD_TOKEN);}
async function shutdown(){for(const module of client.modules.values())try{await module.definition?.destroy?.(client,module.config,module.advanced);}catch(e){console.error(`[Module] Destroy failed for ${module.name}:`,e.message);}try{await client.db?.close?.();}catch{}try{client.destroy();}catch{}process.exit(0);}
if(require.main===module)start().catch(e=>{console.error('[Startup]',e);process.exit(1);});module.exports={client,config,start,deployCommands,executeInteraction};
