const app=document.querySelector('#app');
let state={authed:false,data:null,route:location.hash.slice(1)||'overview',guild:null,module:null,config:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtBytes=n=>{if(!Number.isFinite(n))return'—';const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<3){n/=1024;i++;}return`${n.toFixed(i?1:0)} ${u[i]}`};
const fmtUptime=s=>{s=Number(s||0);const d=Math.floor(s/86400);s%=86400;const h=Math.floor(s/3600);s%=3600;const m=Math.floor(s/60);const parts=[];if(d)parts.push(`${d}d`);if(h)parts.push(`${h}h`);if(m)parts.push(`${m}m`);parts.push(`${s}s`);return parts.join(' ')};
const api=async(path,opts={})=>{const r=await fetch(path,{...opts,headers:{'content-type':'application/json',...(opts.headers||{})}});const data=await r.json().catch(()=>({error:'Invalid server response'}));if(r.status===401){state.authed=false;render();throw new Error('Unauthorized')}if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data};
const toast=(message,bad=false)=>{const el=document.querySelector('#toast');if(!el)return;el.textContent=message;el.className=`fixed bottom-5 right-5 z-50 max-w-sm rounded-xl border px-4 py-3 text-sm shadow-2xl backdrop-blur-xl ${bad?'border-red-500/20 bg-red-500/10 text-red-200':'border-realms-500/20 bg-zinc-900/90 text-zinc-100'}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add('hidden'),3200)};
async function bootstrap(){try{state.data=await api('/api/bootstrap');state.authed=true;render();}catch(e){toast(e.message,true)}}
function icon(t){return`<span class="grid size-8 place-items-center rounded-lg bg-white/5 text-zinc-300">${t}</span>`}
function shell(content){const routes=[['overview','Overview','◈'],['servers','Servers','⌘'],['discord','Discord','◉'],['modules','Modules','◫'],['commands','Commands','›_'],['config','Config','⚙'],['audit','Audit log','≡'],['system','System','◉']];return`<div class="min-h-screen lg:grid lg:grid-cols-[250px_1fr]">
<aside class="border-b border-white/8 bg-zinc-950/70 p-4 lg:sticky lg:top-0 lg:h-screen lg:border-b-0 lg:border-r"><div class="flex items-center gap-3 px-2 py-2"> <div class="grid size-10 place-items-center rounded-2xl bg-realms-500 text-xl font-black shadow-lg shadow-realms-900/30">R</div><div><div class="font-semibold">${esc(state.data.bot)}</div><div class="text-xs text-zinc-500">${esc(state.data.server)} Admin</div></div></div><nav class="mt-7 space-y-1">${routes.map(([id,label,i])=>`<a href="#${id}" class="nav-item ${state.route===id?'active':''}">${icon(i)}<span>${label}</span></a>`).join('')}</nav><div class="mt-6 border-t border-white/8 pt-4"><button class="nav-item w-full" onclick="logout()">${icon('↪')}<span>Sign out</span></button></div><div class="mt-8 rounded-2xl border border-realms-500/10 bg-realms-500/5 p-3 text-xs text-zinc-500">Panel session expires according to its configured lifetime and is cleared when the bot restarts.</div></aside>
<main class="min-w-0"><header class="sticky top-0 z-30 border-b border-white/8 bg-zinc-950/80 px-5 py-4 backdrop-blur-xl"><div class="mx-auto flex max-w-[1500px] items-center justify-between gap-4"><div><div class="text-xs uppercase tracking-[.2em] text-zinc-600">RealmsNetwork / Control Center</div><h1 class="mt-1 text-xl font-semibold">${esc(titleFor(state.route))}</h1></div><div class="flex items-center gap-2"><span class="hidden rounded-full border border-emerald-500/15 bg-emerald-500/10 px-3 py-1.5 text-xs text-emerald-300 sm:inline-flex">● Connected</span><button class="panel-button" onclick="refreshAll()">↻ Refresh</button></div></div></header><div class="mx-auto max-w-[1500px] p-5">${content}</div></main></div><div id="toast" class="hidden"></div>`}
function titleFor(r){return({overview:'Overview',servers:'Server explorer',discord:'Discord management',modules:'Module control',commands:'Command registry',config:'Configuration center',audit:'Audit trail',system:'System & runtime'}[r]||'Admin')}
function stat(label,value,sub){return`<div class="panel-card p-5"><div class="text-xs font-medium uppercase tracking-wider text-zinc-500">${label}</div><div class="stat-value">${esc(value)}</div><div class="mt-1 text-xs text-zinc-600">${esc(sub||'')}</div></div>`}
function overview(){const d=state.data,m=d.memory;return shell(`<div class="space-y-5"><section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">${stat('Guilds',d.guilds,'Discord servers connected')}${stat('Loaded modules',`${d.modulesLoaded}/${d.modulesTotal}`,'Feature modules discovered')}${stat('Commands',d.commands,'Slash + context registry')}${stat('Uptime',fmtUptime(d.uptime),'Current process runtime')}</section><section class="grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><div class="panel-card p-5"><div class="flex items-center justify-between"><div><h2 class="font-semibold">Runtime health</h2><p class="mt-1 text-sm text-zinc-500">Live process and framework telemetry.</p></div><span class="rounded-full bg-realms-500/10 px-3 py-1 text-xs text-realms-300">v${esc(d.version)}</span></div><div class="mt-5 grid gap-3 sm:grid-cols-2">${healthRow('Database',d.database?.type||'unknown',d.database?.remote?'remote':'local')}${healthRow('Shards',d.shards,'active workers')}${healthRow('Memory',fmtBytes(m.heapUsed),`${fmtBytes(m.heapTotal)} heap total`)}${healthRow('Errors',d.metrics.errors,'process lifetime')}${healthRow('Interactions',d.metrics.commands,'commands executed')}${healthRow('Events',d.metrics.events,'gateway events observed')}</div></div><div class="panel-card p-5"><h2 class="font-semibold">Quick actions</h2><div class="mt-4 grid gap-2">${actionButton('↻','Reload commands','reloadCommands()')}${actionButton('⚙','Open config','go(\'config\')')}${actionButton('◫','Manage modules','go(\'modules\')')}${actionButton('⌘','Explore servers','go(\'servers\')')}</div></div></section><section class="panel-card overflow-hidden"><div class="border-b border-white/8 px-5 py-4"><h2 class="font-semibold">Connected servers</h2></div><div class="divide-y divide-white/6">${d.guildList.slice(0,8).map(g=>`<button class="flex w-full items-center gap-3 px-5 py-3 text-left hover:bg-white/4" onclick="openGuild('${g.id}')">${g.icon?`<img src="${esc(g.icon)}" class="size-9 rounded-xl" alt="">`:icon('⌁')}<span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">${esc(g.name)}</span><span class="text-xs text-zinc-600">${g.memberCount} members · ${g.channels} channels</span></span><span class="text-zinc-600">›</span></button>`).join('')||'<div class="p-6 text-sm text-zinc-600">No guilds cached yet.</div>'}</div></section></div>`)}
function healthRow(a,b,c){return`<div class="rounded-xl border border-white/6 bg-black/10 p-3"><div class="text-xs text-zinc-600">${a}</div><div class="mt-1 font-medium text-zinc-100">${esc(b)}</div><div class="text-xs text-zinc-600">${esc(c)}</div></div>`}
function actionButton(i,t,fn){return`<button class="panel-button w-full justify-start" onclick="${fn}">${icon(i)}${t}</button>`}
function servers(){const list=state.data.guildList;return shell(`<div class="grid gap-5 lg:grid-cols-[330px_1fr]"><section class="panel-card overflow-hidden"><div class="border-b border-white/8 p-4"><input id="guildSearch" class="panel-input" placeholder="Search servers" oninput="filterGuilds()"></div><div id="guildList" class="max-h-[70vh] overflow-auto p-2">${list.map(g=>guildCard(g)).join('')}</div></section><section>${state.guild?guildDetail(state.guild):emptyState('Select a server','Inspect channels, roles and cached members for a connected guild.')}</section></div>`)}
function guildCard(g){return`<button data-name="${esc(g.name.toLowerCase())}" class="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-white/5 ${state.guild?.id===g.id?'bg-white/5':''}" onclick="openGuild('${g.id}')">${g.icon?`<img src="${esc(g.icon)}" class="size-10 rounded-xl">`:icon('⌁')}<span class="min-w-0 flex-1"><span class="block truncate text-sm font-medium">${esc(g.name)}</span><span class="text-xs text-zinc-600">${g.memberCount} members</span></span></button>`}
function guildDetail(g){return`<div class="space-y-5"><div class="panel-card flex flex-wrap items-center gap-4 p-5">${g.icon?`<img src="${esc(g.icon)}" class="size-14 rounded-2xl">`:icon('⌁')}<div class="min-w-0 flex-1"><h2 class="truncate text-xl font-semibold">${esc(g.name)}</h2><p class="text-sm text-zinc-500">${g.id} · owner ${g.ownerId}</p></div><div class="grid grid-cols-3 gap-2 text-center text-xs"><div><div class="text-lg font-semibold text-white">${g.memberCount}</div><span class="text-zinc-600">members</span></div><div><div class="text-lg font-semibold text-white">${g.channels.length}</div><span class="text-zinc-600">channels</span></div><div><div class="text-lg font-semibold text-white">${g.roles.length}</div><span class="text-zinc-600">roles</span></div></div></div><div class="grid gap-5 xl:grid-cols-2"><div class="panel-card p-5"><h3 class="font-semibold">Channels</h3><div class="mt-3 space-y-1">${g.channels.map(c=>`<div class="flex items-center gap-2 rounded-lg px-2 py-2 text-sm"><span class="text-zinc-600">${c.type===2?'🔊':'#'}</span><span class="flex-1 truncate">${esc(c.name)}</span><span class="text-xs text-zinc-700">${esc(String(c.type))}</span></div>`).join('')}</div></div><div class="panel-card p-5"><h3 class="font-semibold">Roles</h3><div class="mt-3 space-y-1">${g.roles.map(r=>`<div class="flex items-center gap-2 rounded-lg px-2 py-2 text-sm"><span class="size-2.5 rounded-full" style="background:${esc(r.color)}"></span><span class="flex-1 truncate">${esc(r.name)}</span><span class="text-xs text-zinc-700">${r.position}</span></div>`).join('')}</div></div></div><div class="panel-card p-5"><div class="flex items-center justify-between"><h3 class="font-semibold">Send message</h3><span class="text-xs text-zinc-600">Mentions disabled by panel</span></div><div class="mt-3 grid gap-3 md:grid-cols-[1fr_2fr_auto]"><select id="messageChannel" class="panel-input">${g.channels.filter(c=>[0,5].includes(c.type)).map(c=>`<option value="${c.id}"># ${esc(c.name)}</option>`).join('')}</select><input id="messageContent" class="panel-input" maxlength="2000" placeholder="Type a message as the bot"><button class="panel-button" onclick="sendGuildMessage('${g.id}')">Send</button></div></div></div>`}
function modules(){const mods=state.data.modules;return shell(`<div class="space-y-5"><div class="panel-card flex flex-wrap items-center gap-3 p-4"><input id="moduleSearch" class="panel-input flex-1" placeholder="Search modules" oninput="filterModules()"><span class="text-xs text-zinc-600">${mods.filter(x=>x.enabled).length} enabled · ${mods.length} discovered</span></div><div class="grid gap-3 md:grid-cols-2 xl:grid-cols-3" id="moduleGrid">${mods.map(m=>moduleCard(m)).join('')}</div></div>`)}
function moduleCard(m){return`<article data-name="${esc(m.name.toLowerCase())}" class="panel-card p-4"><div class="flex items-start gap-3"><div class="grid size-10 place-items-center rounded-xl ${m.enabled?'bg-realms-500/15 text-realms-300':'bg-white/5 text-zinc-600'}">◫</div><div class="min-w-0 flex-1"><div class="truncate font-medium">${esc(m.name)}</div><div class="mt-1 text-xs text-zinc-600">${m.loaded?'loaded':'not loaded'} · ${m.commands} commands</div></div><span class="rounded-full px-2.5 py-1 text-[11px] ${m.enabled?'bg-emerald-500/10 text-emerald-300':'bg-white/5 text-zinc-600'}">${m.enabled?'enabled':'disabled'}</span></div><div class="mt-4 flex gap-2"><button class="panel-button flex-1" onclick="toggleModule('${m.name}',${!m.enabled})">${m.enabled?'Disable':'Enable'}</button><button class="panel-button" onclick="openModule('${m.name}')">Details</button></div></article>`}
function commands(){return shell(`<div class="panel-card overflow-hidden"><div class="border-b border-white/8 p-4"><input id="commandSearch" class="panel-input" placeholder="Filter commands by name or description" oninput="filterCommands()"></div><div id="commandList" class="divide-y divide-white/6">${(state.data.commandCache||[]).map(c=>commandRow(c)).join('')||'<div class="p-6 text-sm text-zinc-600">No command data yet. Refresh the registry.</div>'}</div></div>`)}
function commandRow(c){return`<div data-search="${esc((c.name+' '+c.description).toLowerCase())}" class="flex items-center gap-3 px-5 py-3"><div class="grid size-9 place-items-center rounded-lg bg-white/5 text-realms-300">›_</div><div class="min-w-0 flex-1"><div class="font-medium">/${esc(c.name)}</div><div class="truncate text-xs text-zinc-600">${esc(c.description)}</div></div><span class="text-xs text-zinc-600">${c.cooldown?`${c.cooldown}s cooldown`:''}</span></div>`}
function config(){const mods=state.data.modules.map(m=>m.name);const sel=state.module||'dashboard';return shell(`<div class="grid gap-5 lg:grid-cols-[280px_1fr]"><section class="panel-card p-3"><button class="nav-item w-full ${!state.module?'active':''}" onclick="selectConfig('root','basic')">${icon('⚙')}Root config</button><div class="my-2 border-t border-white/6"></div>${mods.map(m=>`<button class="nav-item w-full ${state.module===m?'active':''}" onclick="selectConfig('${m}','basic')">${icon('◫')}<span class="truncate">${esc(m)}</span></button>`).join('')}</section><section class="panel-card min-h-[600px] p-5">${state.config?configEditor():emptyState('Select a config','Pick the root configuration or a module from the left.')}</section></div>`)}
function configEditor(){const c=state.config;return`<div><div class="flex flex-wrap items-center gap-3"><div class="flex-1"><h2 class="font-semibold">${c.scope==='root'?'Root configuration':`${esc(c.module)} configuration`}</h2><p class="mt-1 text-xs text-zinc-600">${esc(c.kind)} · YAML · changes are validated before write</p></div><div class="flex gap-2"><button class="panel-button" onclick="loadConfig('${c.scope}','${c.module||''}','${c.kind==='advanced'?'basic':'advanced'}')">${c.kind==='advanced'?'Basic':'Advanced'}</button><button class="panel-button" onclick="saveConfig()">Save</button></div></div><textarea id="configText" class="code-area mt-5 h-[58vh] w-full resize-y rounded-2xl border border-white/8 bg-zinc-950 p-4 text-xs leading-6 text-zinc-300 outline-none focus:border-realms-500/50">${esc(c.content)}</textarea><p class="mt-2 text-xs text-zinc-600">Core root config and basic module config changes may require a restart.</p></div>`}
function audit(){return shell(`<div class="panel-card overflow-hidden"><div class="border-b border-white/8 px-5 py-4"><h2 class="font-semibold">Recent administrative actions</h2><p class="mt-1 text-sm text-zinc-600">In-memory audit trail for the current process.</p></div><div class="divide-y divide-white/6">${(state.audit||[]).map(x=>`<div class="px-5 py-4"><div class="flex gap-3"><span class="mt-1 size-2 rounded-full bg-realms-500"></span><div class="min-w-0 flex-1"><div class="font-medium">${esc(x.action)}</div><div class="mt-1 text-xs text-zinc-600">${esc(x.at)}${x.module?` · module ${esc(x.module)}`:''}${x.guildId?` · guild ${esc(x.guildId)}`:''}</div></div></div></div>`).join('')||'<div class="p-6 text-sm text-zinc-600">No actions recorded.</div>'}</div></div>`)}
function system(){const d=state.data;return shell(`<div class="grid gap-5 lg:grid-cols-2"><section class="panel-card p-5"><h2 class="font-semibold">Runtime</h2><div class="mt-4 space-y-3">${healthRow('Node',navigator.userAgent.includes('iPhone')?'Browser runtime':'Connected admin client','')}${healthRow('Framework',`v${d.framework}`,d.version)}${healthRow('Environment',d.config.environment,'configured runtime')}${healthRow('Database',d.database?.type||'unknown',d.database?.remote?'shared backend':'local backend')}</div></section><section class="panel-card p-5"><h2 class="font-semibold">Presence</h2><div class="mt-4 grid gap-3"><input id="presenceActivity" class="panel-input" placeholder="Activity text"><select id="presenceStatus" class="panel-input"><option>online</option><option>idle</option><option>dnd</option><option>invisible</option></select><button class="panel-button" onclick="updatePresence()">Update presence</button></div></section><section class="panel-card p-5 lg:col-span-2"><h2 class="font-semibold">Admin panel posture</h2><div class="mt-4 grid gap-3 sm:grid-cols-3"><div class="rounded-xl bg-white/4 p-4"><div class="text-xs text-zinc-600">Bind host</div><div class="mt-1 font-medium">${esc(d.config.adminPanel?.host||'127.0.0.1')}</div></div><div class="rounded-xl bg-white/4 p-4"><div class="text-xs text-zinc-600">Port</div><div class="mt-1 font-medium">${esc(d.config.adminPanel?.port||8787)}</div></div><div class="rounded-xl bg-white/4 p-4"><div class="text-xs text-zinc-600">Writes</div><div class="mt-1 font-medium">${d.config.adminPanel?.readOnly===false?'enabled':'read-only'}</div></div></div></section></div>`)}
function emptyState(title,desc){return`<div class="panel-card grid min-h-[350px] place-items-center p-8 text-center"><div><div class="mx-auto grid size-14 place-items-center rounded-2xl bg-realms-500/10 text-2xl text-realms-300">◈</div><h2 class="mt-4 text-lg font-semibold">${title}</h2><p class="mt-2 max-w-md text-sm text-zinc-600">${desc}</p></div></div>`}
function loginScreen(){app.innerHTML=`<div class="grid min-h-screen place-items-center px-5"><div class="w-full max-w-md"><div class="panel-card p-7"><div class="flex items-center gap-3"><div class="grid size-12 place-items-center rounded-2xl bg-realms-500 text-xl font-black">R</div><div><div class="text-lg font-semibold">RealmsNetwork Admin</div><div class="text-sm text-zinc-500">Secure control center</div></div></div><div class="mt-8"><label class="text-xs uppercase tracking-wider text-zinc-600">Admin token</label><input id="loginToken" class="panel-input mt-2" type="password" autocomplete="current-password" placeholder="Enter DASHBOARD_TOKEN" onkeydown="if(event.key==='Enter')login()"><button class="mt-3 w-full rounded-xl bg-realms-600 px-4 py-3 text-sm font-semibold text-white shadow-lg shadow-realms-950/30 transition hover:bg-realms-500" onclick="login()">Authenticate</button><p id="loginError" class="mt-3 hidden text-sm text-red-300"></p></div></div><p class="mt-4 text-center text-xs text-zinc-700">Local-first administration · no third-party frontend assets</p></div></div>`}
function render(){if(!state.authed)return loginScreen();if(state.route==='overview')app.innerHTML=overview();else if(state.route==='servers')app.innerHTML=servers();else if(state.route==='modules')app.innerHTML=modules();else if(state.route==='commands')app.innerHTML=commands();else if(state.route==='config')app.innerHTML=config();else if(state.route==='audit')app.innerHTML=audit();else app.innerHTML=system()}
async function login(){const input=document.querySelector('#loginToken');const error=document.querySelector('#loginError');try{await api('/api/auth',{method:'POST',body:JSON.stringify({token:input.value})});state.authed=true;await refreshAll();}catch(e){if(error){error.textContent=e.message;error.classList.remove('hidden')}}}
async function logout(){await fetch('/api/logout',{method:'POST'});state.authed=false;state.data=null;render()}
async function refreshAll(){try{state.data=await api('/api/bootstrap');if(state.route==='audit'){const a=await api('/api/audit');state.audit=a.items;}if(state.route==='config'&&state.config)state.config=await api(`/api/config?scope=${state.config.scope}&module=${encodeURIComponent(state.config.module||'')}&kind=${state.config.kind}`);render();}catch(e){toast(e.message,true)}}
function go(route){state.route=route;state.guild=null;location.hash=route;render();if(route==='commands')loadCommands();if(route==='audit')loadAudit();}
async function openGuild(id){try{state.route='servers';state.guild=await api(`/api/guild/${id}`);location.hash='servers';render()}catch(e){toast(e.message,true)}}
function filterGuilds(){const q=document.querySelector('#guildSearch').value.toLowerCase();document.querySelectorAll('#guildList [data-name]').forEach(x=>x.classList.toggle('hidden',!x.dataset.name.includes(q)))}
function filterModules(){const q=document.querySelector('#moduleSearch').value.toLowerCase();document.querySelectorAll('#moduleGrid [data-name]').forEach(x=>x.classList.toggle('hidden',!x.dataset.name.includes(q)))}
function filterCommands(){const q=document.querySelector('#commandSearch').value.toLowerCase();document.querySelectorAll('#commandList [data-search]').forEach(x=>x.classList.toggle('hidden',!x.dataset.search.includes(q)))}
async function toggleModule(name,enabled){try{const r=await api(`/api/module/${encodeURIComponent(name)}/toggle`,{method:'POST',body:JSON.stringify({enabled})});toast(r.message);await refreshAll()}catch(e){toast(e.message,true)}}
async function reloadCommands(){try{const r=await api('/api/reload',{method:'POST'});toast(r.message);await refreshAll()}catch(e){toast(e.message,true)}}
async function loadCommands(){try{state.data.commandCache=(await api('/api/commands')).items;render()}catch(e){toast(e.message,true)}}
async function loadAudit(){try{state.audit=(await api('/api/audit')).items;render()}catch(e){toast(e.message,true)}}
async function selectConfig(module,kind='basic'){state.module=module==='root'?null:module;await loadConfig(module==='root'?'root':'module',module==='root'?'':module,kind)}
async function openModule(name){state.module=name;state.route='config';location.hash='config';await loadConfig('module',name,'basic')}
async function loadConfig(scope,module,kind){try{state.config=await api(`/api/config?scope=${scope}&module=${encodeURIComponent(module||'')}&kind=${kind}`);render()}catch(e){toast(e.message,true)}}
async function saveConfig(){try{const content=document.querySelector('#configText').value;const c=state.config;const r=await api('/api/config',{method:'PUT',body:JSON.stringify({scope:c.scope,module:c.module,kind:c.kind,content})});toast(r.message);await refreshAll()}catch(e){toast(e.message,true)}}
async function sendGuildMessage(id){try{const channelId=document.querySelector('#messageChannel').value,content=document.querySelector('#messageContent').value;const r=await api(`/api/guild/${id}/message`,{method:'POST',body:JSON.stringify({channelId,content})});document.querySelector('#messageContent').value='';toast(`Message sent · ${r.messageId}`)}catch(e){toast(e.message,true)}}
async function updatePresence(){try{const activity=document.querySelector('#presenceActivity').value,status=document.querySelector('#presenceStatus').value;await api('/api/presence',{method:'POST',body:JSON.stringify({activity,status})});toast('Presence updated')}catch(e){toast(e.message,true)}}
window.go=go;window.login=login;window.logout=logout;window.refreshAll=refreshAll;window.refresh=refreshAll;window.openGuild=openGuild;window.filterGuilds=filterGuilds;window.filterModules=filterModules;window.filterCommands=filterCommands;window.toggleModule=toggleModule;window.reloadCommands=reloadCommands;window.selectConfig=selectConfig;window.loadConfig=loadConfig;window.openModule=openModule;window.saveConfig=saveConfig;window.sendGuildMessage=sendGuildMessage;window.updatePresence=updatePresence;
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'overview';render();if(state.route==='commands')loadCommands();if(state.route==='audit')loadAudit()});
api('/api/session').then(r=>{state.authed=r.authenticated;if(state.authed)refreshAll();else render()}).catch(()=>render());
