const fs=require('node:fs');
const path=require('node:path');
const yaml=require('js-yaml');
const root=path.join(__dirname,'..');
const configFile=path.join(root,'config.yml');
const exampleFile=path.join(root,'config.example.yml');
const moduleRoot=path.join(root,'modules');
function deepMerge(base,extra){const out={...(base||{})};for(const[key,value]of Object.entries(extra||{})){if(value&&typeof value==='object'&&!Array.isArray(value))out[key]=deepMerge(out[key],value);else if(!(key in out))out[key]=value;}return out;}
function backup(file){if(!fs.existsSync(file))return;const backup=`${file}.backup.${Date.now()}`;fs.copyFileSync(file,backup);console.log(`[Config] Backup created: ${path.basename(backup)}`);}
function write(file,data){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=`${file}.tmp`;fs.writeFileSync(tmp,data,'utf8');fs.renameSync(tmp,file);}
const legacyAliases={aichat:'ai',honeypot:'security',commandDeployment:'commands'};
function migrate(config){const oldVersion=Number(config.version||1),next={...config};if(next.commandDeployment&&!next.commands)next.commands=next.commandDeployment;if(next.aichat&&!next.ai)next.ai={...next.aichat};if(next.honeypot&&typeof next.honeypot==='object'){if(!next.security||typeof next.security!=='object')next.security={...next.honeypot};else{const legacy=next.honeypot;for(const[key,value]of Object.entries(legacy))if(!(key in next.security))next.security[key]=value;}}if(!next.permissions)next.permissions={};if(!next.runtime)next.runtime={environment:'production',gracefulShutdown:true,crashProtection:true};if(!next.prefix)next.prefix={enabled:false,prefixes:['!'],mentionPrefix:true};if(!next.database)next.database={enabled:false,primary:'none',fallbackToLocal:true};if(!next.sharding)next.sharding={enabled:false,autoDetect:false,totalShards:'auto',shardList:'auto',respawn:true};next.version=5;return{config:next,changed:oldVersion!==5,oldVersion};}
function migrateModuleConfigs(config){if(!fs.existsSync(moduleRoot))return false;let changed=false;for(const[oldName,newName]of Object.entries(legacyAliases)){const data=config[oldName];if(!data||typeof data!=='object')continue;const dir=path.join(moduleRoot,newName),file=path.join(dir,'config.yml');if(!fs.existsSync(dir)||fs.existsSync(file))continue;write(file,yaml.dump({...data,advanced:false},{noRefs:true,lineWidth:-1}));console.log(`[Migration] Created ${newName}/config.yml from legacy ${oldName}`);changed=true;}for(const entry of fs.readdirSync(moduleRoot,{withFileTypes:true}).filter(x=>x.isDirectory())){const name=entry.name,file=path.join(moduleRoot,name,'config.yml');if(!fs.existsSync(file))continue;let data;try{data=yaml.load(fs.readFileSync(file,'utf8'))||{};}catch(e){console.error(`[Migration] Failed to read ${name}/config.yml:`,e.message);continue;}if(!Object.prototype.hasOwnProperty.call(data,'enabled'))continue;const legacyEnabled=data.enabled;delete data.enabled;if(!config[name]||typeof config[name]!=='object')config[name]={};if(typeof config[name].enabled!=='boolean'&&typeof legacyEnabled==='boolean')config[name].enabled=legacyEnabled;backup(file);write(file,yaml.dump(data,{noRefs:true,lineWidth:-1}));console.log(`[Migration] Moved ${name}.enabled=${legacyEnabled} to root config and removed module enabled flag`);changed=true;}const honeypotFile=path.join(moduleRoot,'honeypot','config.yml'),securityFile=path.join(moduleRoot,'security','config.yml');if(fs.existsSync(honeypotFile)&&fs.existsSync(securityFile)){const honeypot=(()=>{try{return yaml.load(fs.readFileSync(honeypotFile,'utf8'))||{};}catch{return{};}})(),security=(()=>{try{return yaml.load(fs.readFileSync(securityFile,'utf8'))||{};}catch{return{};}})();let merged=false;for(const[key,value]of Object.entries(honeypot))if(key!=='aliasOf'&&key!=='enabled'&&!(key in security)){security[key]=value;merged=true;}if(merged){backup(securityFile);write(securityFile,yaml.dump(security,{noRefs:true,lineWidth:-1}));console.log('[Migration] Preserved legacy honeypot settings in security/config.yml');changed=true;}}return changed;}
function loadConfig(){if(!fs.existsSync(configFile)){if(!fs.existsSync(exampleFile))throw new Error('config.example.yml is missing');fs.copyFileSync(exampleFile,configFile);console.log('[Config] Created config.yml from config.example.yml');}let current;try{current=yaml.load(fs.readFileSync(configFile,'utf8'))||{};}catch(e){backup(configFile);current={};console.error('[Config] Invalid config:',e.message);}const example=yaml.load(fs.readFileSync(exampleFile,'utf8'))||{};const migration=migrate(current);const moduleChanged=migrateModuleConfigs(migration.config);const merged=deepMerge(migration.config,example);merged.version=5;if(migration.changed||moduleChanged){if(fs.existsSync(configFile))backup(configFile);write(configFile,yaml.dump(merged,{noRefs:true,lineWidth:-1}));if(migration.changed)console.log(`[Config] Migrated V${migration.oldVersion} -> V5`);if(moduleChanged)console.log('[Config] Module enable states are now controlled by root config.yml');}return merged;}
module.exports={loadConfig,migrate,deepMerge,migrateModuleConfigs};
