const fs=require('node:fs');
const path=require('node:path');
const yaml=require('js-yaml');
const {buildCommands,buildListeners,loadCustomModule}=require('./custom-dsl');
const root=path.join(__dirname,'..'),moduleRoot=path.join(root,'modules'),customRoot=path.join(root,'custom-modules');
function readYaml(file,fallback={}){try{return yaml.load(fs.readFileSync(file,'utf8'))||fallback;}catch(e){console.error(`[Config] Failed ${file}:`,e.message);return fallback;}}
function mergeDefaults(defaults,inherited){const out={...defaults,...(inherited||{})};for(const[key,value]of Object.entries(defaults||{}))if(value&&typeof value==='object'&&!Array.isArray(value)&&inherited?.[key]&&typeof inherited[key]==='object')out[key]=mergeDefaults(value,inherited[key]);return out;}
function ensureModuleConfig(dir,inherited={}){const file=path.join(dir,'config.yml');if(!fs.existsSync(file)){fs.writeFileSync(file,yaml.dump(mergeDefaults({enabled:false},inherited),{noRefs:true,lineWidth:-1}),'utf8');console.log(`[Config] Created ${file}`);}return readYaml(file,mergeDefaults({enabled:false},inherited));}
function moduleFile(dir){return fs.existsSync(path.join(dir,'module.js'))?path.join(dir,'module.js'):path.join(dir,'index.js');}
function validCommand(x){return x?.data?.name&&typeof x.execute==='function';}
function addCommands(client,commands){for(const command of Array.isArray(commands)?commands:[])if(validCommand(command))client.commands.set(command.data.name,command);}
function addContextMenus(client,items){for(const item of Array.isArray(items)?items:[])if(validCommand(item))client.contextMenus.set(item.data.name,item);}
async function loadOne(client,name,dir,rootConfig,custom=false){const dsl=custom?loadCustomModule(dir):null,moduleConfig=ensureModuleConfig(dir,rootConfig[name]||{});if(custom&&dsl?.enabled===true)moduleConfig.enabled=true;if(moduleConfig.enabled!==true)return false;try{if(dsl){addCommands(client,buildCommands(dsl));for(const listener of buildListeners(dsl))client.on(listener.event,(...args)=>listener.handle(...args));client.modules.set(name,{name,config:moduleConfig,definition:dsl,type:'yaml',dir});return true;}const file=moduleFile(dir);if(!fs.existsSync(file))return false;delete require.cache[require.resolve(file)];const mod=require(file),config={...rootConfig,[name]:moduleConfig};if(typeof mod.initialize==='function')await mod.initialize(client,config,moduleConfig);addCommands(client,mod.commands);addContextMenus(client,mod.contextMenus);if(Array.isArray(mod.listeners))for(const listener of mod.listeners)if(listener?.event&&typeof listener.handle==='function')client.on(listener.event,(...args)=>listener.handle(...args,client));client.modules.set(name,{name,config:moduleConfig,definition:mod,type:'javascript',dir,file});return true;}catch(error){console.error(`[Module] Failed to load ${name}:`,error);return false;}}
function moduleDirectories(base){if(!fs.existsSync(base))return[];return fs.readdirSync(base,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>[x.name,path.join(base,x.name)]).sort((a,b)=>a[0].localeCompare(b[0]));}
async function loadCustomModules(client){if(client.config.customModules?.enabled===false)return;for(const[name,dir]of moduleDirectories(customRoot))await loadOne(client,name,dir,client.config,true);}
async function loadModules(client,config){for(const[name,dir]of moduleDirectories(moduleRoot))await loadOne(client,name,dir,config,false);await loadCustomModules(client);}
async function refreshCommands(client,config,silent=false){const next=new Map(),menus=new Map();for(const[name,dir]of[...moduleDirectories(moduleRoot),...moduleDirectories(customRoot)]){const dsl=loadCustomModule(dir),local=ensureModuleConfig(dir,config[name]||{});if(dsl?.enabled===true)local.enabled=true;if(local.enabled!==true)continue;if(dsl){for(const c of buildCommands(dsl))next.set(c.data.name,c);continue;}const file=moduleFile(dir);if(!fs.existsSync(file))continue;for(const c of require(file).commands||[])if(validCommand(c))next.set(c.data.name,c);for(const c of require(file).contextMenus||[])if(validCommand(c))menus.set(c.data.name,c);}client.commands.clear();for(const[name,c]of next)client.commands.set(name,c);client.contextMenus.clear();for(const[name,c]of menus)client.contextMenus.set(name,c);if(!silent)console.log(`[Commands] Refreshed ${client.commands.size+client.contextMenus.size} local commands`);return client.commands;}
module.exports={loadModules,loadCustomModules,refreshCommands,readYaml,ensureModuleConfig,moduleDirectories};
