const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const { refreshCommands } = require('../../lib/module-loader');
const commands = [
  { data: new SlashCommandBuilder().setName('help').setDescription('Show available RealmsNetwork Bot features').addStringOption(o=>o.setName('module').setDescription('Show one module')), execute: async (i,client)=>{const wanted=i.options.getString('module');const mods=[...client.modules.values()];if(wanted){const m=client.modules.get(wanted);if(!m)return i.reply({content:`Module \`${wanted}\` is not loaded.`,ephemeral:true});const names=Array.from(m.definition?.commands||m.definition?.commands||[]).map(x=>x.data?.name).filter(Boolean);return i.reply({content:`**${m.name}**\nType: ${m.type}\nCommands: ${names.length?names.map(x=>`/${x}`).join(', '):'none'}`,ephemeral:true});}const text=mods.map(m=>`**${m.name}** • ${m.type}`).join('\n')||'No modules loaded.';await i.reply({embeds:[new EmbedBuilder().setTitle(`${client.config.branding?.serverName||'RealmsNetwork'} Bot`).setDescription(text.slice(0,4000)).setFooter({text:`${client.commands.size+client.contextMenus.size} commands • ${mods.length} modules`}).setColor(client.config.branding?.embedColor||'#8b5cf6')}]}); } },
  { data: new SlashCommandBuilder().setName('modules').setDescription('List loaded modules'), execute: async(i,client)=>i.reply({content:[...client.modules.keys()].map(x=>`• \`${x}\``).join('\n')||'None',ephemeral:true}) },
  { data: new SlashCommandBuilder().setName('botstats').setDescription('Show runtime and command statistics'), execute: async(i,client)=>{const up=Math.floor((Date.now()-client.metrics.startedAt)/1000);await i.reply({content:`🧩 Modules: **${client.modules.size}**\n⚡ Commands: **${client.commands.size+client.contextMenus.size}**\n📨 Executions: **${client.metrics.commands}**\n❌ Errors: **${client.metrics.errors}**\n🏠 Guilds: **${client.guilds.cache.size}**\n⏱️ Uptime: **${up}s**\n🏓 Ping: **${client.ws.ping}ms**`,ephemeral:true});} },
  { data: new SlashCommandBuilder().setName('reload').setDescription('Refresh command definitions'), requiredPermission: PermissionFlagsBits.ManageGuild, execute: async(i,client)=>{await refreshCommands(client,client.config);await i.reply({content:`✅ Reloaded **${client.commands.size}** slash commands.`,ephemeral:true});} }
];
module.exports={commands};
