const { SlashCommandBuilder, PermissionFlagsBits, EmbedBuilder } = require('discord.js');
const { refreshCommands } = require('../../lib/module-loader');
function brand(client){const b=client.config.branding||{};return{server:b.serverName||'RealmsNetwork',bot:b.botName||'RealmsNetwork Bot',color:b.embedColor||'#8b5cf6',footer:b.footer||b.serverName||'RealmsNetwork'};}
function embed(client,title,description){const b=brand(client);return new EmbedBuilder().setColor(b.color).setTitle(title).setDescription(description).setTimestamp().setFooter({text:b.footer});}
const commands=[
{data:new SlashCommandBuilder().setName('help').setDescription('Show available bot features').addStringOption(o=>o.setName('module').setDescription('Show one module')),execute:async(i,client)=>{const b=brand(client),wanted=i.options.getString('module');if(wanted){const m=client.modules.get(wanted);if(!m)return i.reply({content:`${b.server}: module \`${wanted}\` is not loaded.`,ephemeral:true});const names=Array.from(m.definition?.commands||[]).map(x=>x.data?.name).filter(Boolean);return i.reply({embeds:[embed(client,`${b.server} • ${m.name}`,`**Type:** ${m.type}\n**Commands:** ${names.length?names.map(x=>`/${x}`).join(', '):'none'}`)],ephemeral:true});}const text=[...client.modules.values()].map(m=>`**${m.name}** • ${m.type}`).join('\n')||'No modules are loaded.';return i.reply({embeds:[embed(client,b.bot,text).setFooter({text:`${b.footer} • ${client.commands.size+client.contextMenus.size} commands • ${client.modules.size} modules`})]});}},
{data:new SlashCommandBuilder().setName('modules').setDescription('List loaded modules'),execute:async(i,client)=>{const b=brand(client);return i.reply({embeds:[embed(client,`${b.server} • Modules`,[...client.modules.keys()].map(x=>`• \`${x}\``).join('\n')||'None')],ephemeral:true});}},
{data:new SlashCommandBuilder().setName('botstats').setDescription('Show runtime and command statistics'),execute:async(i,client)=>{const b=brand(client),uptime=Math.floor((Date.now()-client.metrics.startedAt)/1000);return i.reply({embeds:[embed(client,`${b.bot} • Statistics`,`🧩 Modules: **${client.modules.size}**\n⚡ Commands: **${client.commands.size+client.contextMenus.size}**\n📨 Executions: **${client.metrics.commands}**\n❌ Errors: **${client.metrics.errors}**\n🏠 Guilds: **${client.guilds.cache.size}**\n⏱️ Uptime: **${uptime}s**\n🏓 Ping: **${client.ws.ping}ms**`)],ephemeral:true});}},
{data:new SlashCommandBuilder().setName('reload').setDescription('Refresh command definitions'),requiredPermission:PermissionFlagsBits.ManageGuild,execute:async(i,client)=>{await refreshCommands(client,client.config);const b=brand(client);return i.reply({embeds:[embed(client,`${b.server} • Reloaded`,`Reloaded **${client.commands.size}** slash commands.`)],ephemeral:true});}}
];
module.exports={commands};
