const { EmbedBuilder, SlashCommandBuilder } = require('discord.js');
const cache={at:0,countries:[]};
function cfg(client){return client.modules.get('countryballs')?.config||{};}
function nameOf(b){return b?.names?.common||b?.name?.common||b?.name||'Unknown';}
function flagOf(b){return b?.flag?.emoji||'';}
function codeOf(b){return b?.codes?.alpha_2||b?.cca2||'';}
function imageOf(b){return b?.flag?.png||b?.flags?.png||null;}
async function loadCountries(client,force=false){const c=cfg(client),ttl=Math.max(60,Number(c.api?.cacheMinutes||360))*60000;if(!force&&cache.countries.length&&Date.now()-cache.at<ttl)return cache.countries;const base=String(c.api?.baseUrl||'https://api.restcountries.com/countries/v5').replace(/\/$/,'');const url=`${base}?limit=100&response_fields=${encodeURIComponent(c.api?.fields||'names.common,names.official,codes.alpha_2,codes.alpha_3,flag.emoji,flag.png,population,region,subregion,capitals,currencies,languages,timezones')}`;const headers={};const key=c.api?.apiKeyEnv?process.env[c.api.apiKeyEnv]:process.env.REST_COUNTRIES_API_KEY;if(key)headers.authorization=`Bearer ${key}`;const r=await fetch(url,{headers});if(!r.ok)throw new Error(`Country API HTTP ${r.status}`);const payload=await r.json();cache.countries=(payload?.data?.objects||payload?.data||[]).filter(x=>x?.names?.common||x?.name?.common||x?.name);cache.at=Date.now();return cache.countries;}
function rarityIndex(ball,countries){const ratio=Math.max(0,countries.indexOf(ball))/Math.max(1,countries.length-1);return ratio<.6?'Common':ratio<.85?'Uncommon':ratio<.95?'Rare':ratio<.99?'Epic':'Legendary';}
async function profile(db,guildId,userId){return db.get(guildId,`countryballs:${userId}`,{coins:100,collection:{},favorites:[]});}
const command=new SlashCommandBuilder().setName('ball').setDescription('Countryball collection and game').addSubcommand(s=>s.setName('roll').setDescription('Collect a countryball')).addSubcommand(s=>s.setName('search').setDescription('Find a country').addStringOption(o=>o.setName('query').setDescription('Country name or code').setRequired(true))).addSubcommand(s=>s.setName('profile').setDescription('View your collection')).addSubcommand(s=>s.setName('dex').setDescription('Show live country data')).addSubcommand(s=>s.setName('refresh').setDescription('Refresh the country API cache'));
async function execute(i,client){const sub=i.options.getSubcommand();if(sub==='refresh'){const data=await loadCountries(client,true);return i.reply(`🌎 Refreshed **${data.length}** countries from the configured API.`);}const countries=await loadCountries(client);if(sub==='search'){const q=i.options.getString('query',true).toLowerCase();const found=countries.find(x=>nameOf(x).toLowerCase().includes(q)||codeOf(x).toLowerCase()===q);if(!found)return i.reply({content:'Country not found.',ephemeral:true});const e=new EmbedBuilder().setColor(cfg(client).ui?.embedColor||client.config.branding.embedColor).setTitle(`${flagOf(found)} ${nameOf(found)}`).addFields({name:'ISO',value:codeOf(found)||'N/A',inline:true},{name:'Region',value:String(found.region||'N/A'),inline:true},{name:'Population',value:Number(found.population||0).toLocaleString(),inline:true});if(found.capitals?.[0]?.name)e.addFields({name:'Capital',value:found.capitals[0].name,inline:true});if(imageOf(found))e.setThumbnail(imageOf(found));return i.reply({embeds:[e]});}if(sub==='dex')return i.reply(`🌎 Live country index: **${countries.length}** countries. Use /ball search with a country name or ISO code.`);if(sub==='profile'){const p=await profile(client.db,i.guildId,i.user.id),entries=Object.entries(p.collection).sort((a,b)=>b[1]-a[1]);return i.reply(`🌎 ${i.user} owns **${entries.reduce((n,[,v])=>n+v,0)}** ${cfg(client).collection?.pluralName||'countryballs'} across **${entries.length}** countries.\n${entries.slice(0,20).map(([k,v])=>`• ${k}: ${v}`).join('\n')||'No collection yet.'}`);}const p=await profile(client.db,i.guildId,i.user.id),cost=10;if(p.coins<cost)return i.reply({content:`You need ${cost} coins. You have ${p.coins}.`,ephemeral:true});const ball=countries[Math.floor(Math.random()*countries.length)],name=nameOf(ball);p.coins-=cost;p.collection[name]=(p.collection[name]||0)+1;await client.db.set(i.guildId,`countryballs:${i.user.id}`,p);const e=new EmbedBuilder().setColor(cfg(client).ui?.embedColor||client.config.branding.embedColor).setTitle(`${flagOf(ball)} Countryball Caught`).setDescription(`${i.user} caught **${name}**!\n\n**Rarity:** ${rarityIndex(ball,countries)}\n**Copies:** ${p.collection[name]}\n**Coins:** ${p.coins}`);if(imageOf(ball))e.setThumbnail(imageOf(ball));return i.reply({embeds:[e]});}
async function initialize(client){client.countryballs={loadCountries:force=>loadCountries(client,force),profile};loadCountries(client).catch(e=>console.warn('[Countryballs] API:',e.message));}
module.exports={initialize,commands:[{data:command,execute}]};
