const { EmbedBuilder, SlashCommandBuilder } = require('discord.js');
const cache={at:0,countries:[]};
function cfg(client){return client.modules.get('countryballs')?.config||{};}
function nameOf(b){return b?.names?.common||b?.name?.common||b?.name||'Unknown';}
function flagOf(b){return b?.flag?.emoji||'';}
function codeOf(b){return b?.codes?.alpha_2||b?.cca2||'';}
function imageOf(b){return b?.flag?.png||b?.flags?.png||null;}
async function loadCountries(client,force=false){const c=cfg(client),ttl=Math.max(60,Number(c.api?.cacheMinutes||360))*60000;if(!force&&cache.countries.length&&Date.now()-cache.at<ttl)return cache.countries;const base=String(c.api?.baseUrl||'https://api.restcountries.com/countries/v5').replace(/\/$/,'');const url=`${base}?limit=100&response_fields=${encodeURIComponent(c.api?.fields||'names.common,names.official,codes.alpha_2,codes.alpha_3,flag.emoji,flag.png,population,region,subregion,continents,borders,capitals,currencies,languages,timezones,demonyms')}`;const headers={};const env=c.api?.apiKeyEnv||'REST_COUNTRIES_API_KEY';const key=process.env[env]||(c.api?.useDemoKeyWhenUnset?'rc_live_demo':'');if(key)headers.authorization=`Bearer ${key}`;const r=await fetch(url,{headers});if(!r.ok)throw new Error(`Country API HTTP ${r.status}`);const payload=await r.json();cache.countries=(payload?.data?.objects||payload?.data||[]).filter(x=>x?.names?.common||x?.name?.common||x?.name);cache.at=Date.now();return cache.countries;}
function rarityIndex(ball,countries){const ratio=Math.max(0,countries.indexOf(ball))/Math.max(1,countries.length-1);return ratio<.6?'Common':ratio<.85?'Uncommon':ratio<.95?'Rare':ratio<.99?'Epic':'Legendary';}
async function profile(db,guildId,userId){return db.get(guildId,`countryballs:${userId}`,{coins:100,collection:{},favorites:[],lastDaily:0});}
const command=new SlashCommandBuilder().setName('ball').setDescription('Countryball collection and game').addSubcommand(s=>s.setName('roll').setDescription('Collect a random countryball')).addSubcommand(s=>s.setName('search').setDescription('Find a country').addStringOption(o=>o.setName('query').setDescription('Country name or ISO code').setRequired(true))).addSubcommand(s=>s.setName('profile').setDescription('View your collection')).addSubcommand(s=>s.setName('dex').setDescription('Show live country data')).addSubcommand(s=>s.setName('favorite').setDescription('Favorite a collected countryball').addStringOption(o=>o.setName('country').setDescription('Country name').setRequired(true))).addSubcommand(s=>s.setName('leaderboard').setDescription('Show collection leaderboard')).addSubcommand(s=>s.setName('daily').setDescription('Claim daily countryball coins')).addSubcommand(s=>s.setName('refresh').setDescription('Refresh the country API cache')).addSubcommand(s=>s.setName('gift').setDescription('Gift one countryball to another player').addUserOption(o=>o.setName('user').setDescription('Recipient').setRequired(true)).addStringOption(o=>o.setName('country').setDescription('Countryball name').setRequired(true)));
async function execute(i,client){const c=cfg(client),sub=i.options.getSubcommand(),countries=await loadCountries(client);if(sub==='refresh'){const data=await loadCountries(client,true);return i.reply(`🌎 Refreshed **${data.length}** countries from the configured API.`);}if(sub==='search'){const q=i.options.getString('query',true).toLowerCase();const found=countries.find(x=>nameOf(x).toLowerCase().includes(q)||codeOf(x).toLowerCase()===q);if(!found)return i.reply({content:'Country not found.',ephemeral:true});const e=new EmbedBuilder().setColor(c.ui?.embedColor||client.config.branding.embedColor).setTitle(`${flagOf(found)} ${nameOf(found)}`).addFields({name:'ISO',value:codeOf(found)||'N/A',inline:true},{name:'Region',value:String(found.region||'N/A'),inline:true},{name:'Population',value:Number(found.population||0).toLocaleString(),inline:true});if(found.capitals?.[0]?.name)e.addFields({name:'Capital',value:String(found.capitals[0].name),inline:true});if(imageOf(found))e.setThumbnail(imageOf(found));return i.reply({embeds:[e]});}
if(sub==='dex')return i.reply(`🌎 Live country index: **${countries.length}** records from the configured country API.`);
if(sub==='profile'){const p=await profile(client.db,i.guildId,i.user.id),entries=Object.entries(p.collection||{}).sort((a,b)=>b[1]-a[1]);return i.reply(`🌎 ${i.user} owns **${entries.reduce((n,[,v])=>n+v,0)}** ${c.collection?.pluralName||'countryballs'} across **${entries.length}** countries.\n⭐ Favorites: **${(p.favorites||[]).length}**\n🪙 Coins: **${p.coins||0}**\n${entries.slice(0,20).map(([k,v])=>`• ${k}: ${v}`).join('\n')||'No collection yet.'}`);}
if(sub==='favorite'){if(c.features?.favorites===false)return i.reply({content:'Favorites are disabled.',ephemeral:true});const country=i.options.getString('country',true),p=await profile(client.db,i.guildId,i.user.id);if(!p.collection?.[country])return i.reply({content:'You do not own that countryball.',ephemeral:true});p.favorites=p.favorites||[];if(p.favorites.includes(country))p.favorites=p.favorites.filter(x=>x!==country);else{if(p.favorites.length>=Number(c.collection?.maxFavorites||50))return i.reply({content:'Your favorites are full.',ephemeral:true});p.favorites.push(country);}await client.db.set(i.guildId,`countryballs:${i.user.id}`,p);return i.reply(`⭐ ${p.favorites.includes(country)?'Favorited':'Unfavorited'} **${country}**.`);}
if(sub==='daily'){const p=await profile(client.db,i.guildId,i.user.id),now=Date.now();if(now-(p.lastDaily||0)<86400000)return i.reply({content:`Daily already claimed. Try again <t:${Math.floor((p.lastDaily+86400000)/1000)}:R>.`,ephemeral:true});const reward=250;p.coins=(p.coins||0)+reward;p.lastDaily=now;await client.db.set(i.guildId,`countryballs:${i.user.id}`,p);return i.reply(`🎁 You claimed **${reward}** coins. Balance: **${p.coins}**.`);}
if(sub==='leaderboard'){const members=await i.guild.members.fetch();const rows=[];for(const m of members.values()){if(m.user.bot)continue;const p=await profile(client.db,i.guildId,m.id);rows.push({name:m.user.displayName||m.user.username,count:Object.values(p.collection||{}).reduce((n,v)=>n+Number(v),0)});}rows.sort((a,b)=>b.count-a.count);return i.reply(rows.slice(0,10).map((x,n)=>`**${n+1}.** ${x.name} — ${x.count}`).join('\n')||'No collection data yet.');}
if(sub==='gift'){if(c.features?.trading===false)return i.reply({content:'Trading/gifting is disabled.',ephemeral:true});const user=i.options.getUser('user',true),country=i.options.getString('country',true),target=await profile(client.db,i.guildId,user.id),own=await profile(client.db,i.guildId,i.user.id);if(user.bot||user.id===i.user.id)return i.reply({content:'Choose another human player.',ephemeral:true});if(!own.collection?.[country])return i.reply({content:'You do not own that countryball.',ephemeral:true});own.collection[country]--;if(own.collection[country]<=0)delete own.collection[country];target.collection=target.collection||{};target.collection[country]=(target.collection[country]||0)+1;await client.db.set(i.guildId,`countryballs:${i.user.id}`,own);await client.db.set(i.guildId,`countryballs:${user.id}`,target);return i.reply(`🎁 Gifted **${country}** to ${user}.`);}
const p=await profile(client.db,i.guildId,i.user.id),cost=Number(c.collection?.catchCost||10);if(p.coins<cost)return i.reply({content:`You need ${cost} coins. You have ${p.coins}.`,ephemeral:true});const ball=countries[Math.floor(Math.random()*countries.length)],name=nameOf(ball);p.coins-=cost;p.collection[name]=(p.collection[name]||0)+1;await client.db.set(i.guildId,`countryballs:${i.user.id}`,p);const e=new EmbedBuilder().setColor(c.ui?.embedColor||client.config.branding.embedColor).setTitle(`${flagOf(ball)} Countryball Caught`).setDescription(`${i.user} caught **${name}**!\n\n**Rarity:** ${rarityIndex(ball,countries)}\n**Copies:** ${p.collection[name]}\n**Coins:** ${p.coins}`);if(imageOf(ball))e.setThumbnail(imageOf(ball));return i.reply({embeds:[e]});}
async function initialize(client){client.countryballs={loadCountries:force=>loadCountries(client,force),profile};loadCountries(client).catch(e=>console.warn('[Countryballs] API:',e.message));}
module.exports={initialize,commands:[{data:command,execute}]};
