const { SlashCommandBuilder, EmbedBuilder } = require('discord.js');

const sleep = ms => new Promise(r => setTimeout(r, ms));
async function json(url, options = {}) { const response = await fetch(url, { redirect: 'follow', ...options }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error?.message || data?.message || `HTTP ${response.status}`); return data; }
async function openAIStyle(cfg, messages, envKey = null) { const key = cfg.apiKey || (envKey ? process.env[envKey] : ''); const base = String(cfg.baseUrl || '').replace(/\/$/, ''); if (!base) throw new Error('AI baseUrl is missing'); const headers = { 'content-type': 'application/json' }; if (key) headers.authorization = `Bearer ${key}`; const data = await json(`${base}/chat/completions`, { method: 'POST', headers, body: JSON.stringify({ model: cfg.model, messages, temperature: cfg.temperature, max_tokens: cfg.maxTokens, stream: false }) }); return data?.choices?.[0]?.message?.content || ''; }
async function gemini(cfg, messages) { const key = cfg.apiKey || process.env.GEMINI_API_KEY; if (!key) throw new Error('GEMINI_API_KEY is missing'); const model = cfg.model || 'gemini-2.5-flash'; const contents = messages.filter(x => x.role !== 'system').map(x => ({ role: x.role === 'assistant' ? 'model' : 'user', parts: [{ text: x.content }] })); const system = messages.find(x => x.role === 'system')?.content; const body = { contents, generationConfig: { temperature: cfg.temperature, maxOutputTokens: cfg.maxTokens } }; if (system) body.systemInstruction = { parts: [{ text: system }] }; const data = await json(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); return data?.candidates?.[0]?.content?.parts?.map(x => x.text || '').join('') || ''; }
async function anthropic(cfg, messages) { const key = cfg.apiKey || process.env.ANTHROPIC_API_KEY; if (!key) throw new Error('ANTHROPIC_API_KEY is missing'); const system = messages.find(x => x.role === 'system')?.content; const body = { model: cfg.model, max_tokens: cfg.maxTokens || 1200, temperature: cfg.temperature, messages: messages.filter(x => x.role !== 'system') }; if (system) body.system = system; const response = await fetch(`${String(cfg.baseUrl || 'https://api.anthropic.com').replace(/\/$/, '')}/v1/messages`, { method: 'POST', headers: { 'content-type': 'application/json', 'x-api-key': key, 'anthropic-version': cfg.version || '2023-06-01' }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data?.error?.message || `HTTP ${response.status}`); return data?.content?.map(x => x.text || '').join('') || ''; }

const providers = {
  openai: cfg => openAIStyle(cfg, cfg.messages, 'OPENAI_API_KEY'), groq: cfg => openAIStyle(cfg, cfg.messages, 'GROQ_API_KEY'), mistral: cfg => openAIStyle(cfg, cfg.messages, 'MISTRAL_API_KEY'), deepseek: cfg => openAIStyle(cfg, cfg.messages, 'DEEPSEEK_API_KEY'), xai: cfg => openAIStyle(cfg, cfg.messages, 'XAI_API_KEY'), together: cfg => openAIStyle(cfg, cfg.messages, 'TOGETHER_API_KEY'), openrouter: cfg => openAIStyle(cfg, cfg.messages, 'OPENROUTER_API_KEY'), perplexity: cfg => openAIStyle(cfg, cfg.messages, 'PERPLEXITY_API_KEY'), cohere: cfg => openAIStyle(cfg, cfg.messages, 'COHERE_API_KEY'), huggingface: cfg => openAIStyle(cfg, cfg.messages, 'HF_TOKEN'), openai_compatible: cfg => openAIStyle(cfg, cfg.messages, cfg.apiKeyEnv || null), lmstudio: cfg => openAIStyle({ ...cfg, baseUrl: cfg.baseUrl || 'http://127.0.0.1:1234/v1' }, cfg.messages), ollama: cfg => openAIStyle({ ...cfg, baseUrl: cfg.baseUrl || 'http://127.0.0.1:11434/v1' }, cfg.messages)
};

async function chat(config, messages) { const cfg = { ...config, messages }; const order = [cfg.provider, ...(cfg.fallbackProviders || [])].filter(Boolean); let last; for (const name of order) { try { const providerCfg = { ...(cfg.providers?.[name] || {}), ...cfg, ...(cfg.providers?.[name] || {}) }; providerCfg.messages = messages; providerCfg.model ||= cfg.model; if (name === 'gemini') return await gemini(providerCfg, messages); if (name === 'anthropic') return await anthropic(providerCfg, messages); if (providers[name]) return await providers[name](providerCfg); } catch (e) { last = e; if (cfg.retryDelayMs) await sleep(Math.min(10000, Number(cfg.retryDelayMs))); } } throw last || new Error('No configured AI provider worked'); }

function command() { return { data: new SlashCommandBuilder().setName('ask').setDescription('Ask the configured AI provider').addStringOption(o => o.setName('prompt').setDescription('Your prompt').setRequired(true)), execute: async (interaction, client) => { const cfg = client.config.ai || {}; const prompt = interaction.options.getString('prompt', true).slice(0, Number(cfg.maxInputLength || 6000)); await interaction.deferReply(); try { const text = await chat(cfg, [{ role: 'system', content: cfg.systemPrompt || `You are a helpful Discord assistant for ${client.config.branding?.serverName || 'this server'}.` }, { role: 'user', content: prompt }]); await interaction.editReply({ content: text.slice(0, 4000) || 'The AI returned an empty response.' }); } catch (e) { await interaction.editReply({ content: cfg.errorMessage || `AI error: ${e.message}` }); } } }; }
function providerCommand() { return { data: new SlashCommandBuilder().setName('aiprovider').setDescription('Show the active AI provider'), execute: async (interaction, client) => { const cfg = client.config.ai || {}; const embed = new EmbedBuilder().setTitle('AI Provider').setColor(client.config.branding?.embedColor || '#8b5cf6').addFields({ name: 'Primary', value: String(cfg.provider || 'none'), inline: true }, { name: 'Fallbacks', value: (cfg.fallbackProviders || []).join(', ') || 'None', inline: true }, { name: 'Model', value: String(cfg.model || 'unset'), inline: true }); await interaction.reply({ embeds: [embed], ephemeral: true }); } }; }
async function initialize(client, config, moduleConfig) { client.ai = { chat: (messages, override = {}) => chat({ ...(config.ai || {}), ...moduleConfig, ...override }, messages) }; }
module.exports = { initialize, commands: [command(), providerCommand()] };
